### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007000E

### ISSUE THREAD

**Issue by SpiritGun91** [sevcator/ASF-Android#1]
![Screenshot_20230729-232530_crDroid Home](https://github.com/sevcator/ASF-Android/assets/101740573/a3acc727-3ff5-4c76-89bc-937a6c5b670a)
I followed the setup instructions on the ASF GitHub and put my json file in the config folder as well, but I get this error. Not sure if this is issue should be in the ASF GitHub or here, forgive my ignorance lol thanks in advance.

**Comment by sevcator** [comment]
enter this:

export DOTNET_GCHeapHardLimit=1C0000000 && /home/noroot/asf/ArchiSteamFarm

**Comment by SpiritGun91** [comment]
That worked!
