### ISSUE TITLE
Typing "bash" activates ASF instead of switching to bash shell

### ISSUE THREAD

**Issue by SpiritGun91** [sevcator/ASF-Android#2]
After running the install script, if I type "bash" in termux, it runs ASF instead of just switching to bash shell. I did use LitMux to configure my Termux, so I run zsh by default. Maybe it's an issue on my end due to that, if so my bad lol.

**Comment by SpiritGun91** [comment]
I can also ctrl-c out of it and it's in bash shell so really it's all good lol

**Comment by sevcator** [comment]
If IPC server is launched like 127.0.0.1:1337, you can open new session in termux and use.

**Comment by SpiritGun91** [comment]
Awesome thnx again.
